Repository nipype/pydra-ml, pull requests merged in 2021-08, with the labels that each got.

#40 enhance testing matrix
  .github/workflows/ci.yml
Labels: internal

#43 cleaner v03: empirical p-value, performance table, README, feature_importance and permutation_importance
  README.md
  examples/classification_cancer_long-spec.json
  examples/classification_cancer_short-spec.json
  examples/classification_cancer_toy-spec.json
  examples/regression_diabetes_spec.json
  examples/shap_example.png
  examples/test-roc_auc_score-example.png
  examples/test_performance_with_null_roc_auc_score.png
  pydra_ml/classifier.py
  pydra_ml/report.py
  pydra_ml/tasks.py
  pydra_ml/tests/test_classifier.py
Labels: release, minor

#44 Add MANIFEST.in to help pypi publishing
  MANIFEST.in
Labels: patch, release
